spring.application.name=polltaker


# RFC 9457 / Problem Details
spring.mvc.problemdetails.enabled=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# Configuração de persistência em arquivo local para o H2
spring.datasource.url=jdbc:h2:file:./data/polltakerdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console do H2 para inspeção dos dados
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do Hibernate para manter a estrutura e preservar os dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true